development:
  adapter: postgresql
  database: reportbooru 
  pool: 5

test:
  adapter: postgresql
  database: reportbooru_test
  pool: 5

production:
  adapter: postgresql
  database: reportbooru
  pool: 5
