development:
  adapter: postgresql
  database: danbooru2 
  pool: 5

test:
  adapter: postgresql
  database: danbooru2_test
  pool: 5

production:
  adapter: postgresql
  database: danbooru2
  pool: 5
