development:
  adapter: postgresql
  database: reportbooru 
  pool: 5

test:
  adapter: postgresql
  database: reportbooru_test
  pool: 5

production:
  adapter: postgresql
  database: reportbooru
  pool: 5

danbooru_development:
  adapter: postgresql
  database: danbooru2

danbooru_production:
  adapter: postgresql
  database: danbooru2
  username: danbooru_ro
  host: yukinoshita
  password: <%= ENV["DANBOORU_RO_PASSWORD"] %>
