# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68b61b46013861e4dd4dd6003211074a2d463b2cd0eadd5f23b6606406104b4c7dd041a66bc228a564b540ce87b01390c6c44557b11bb33de5a218e7252986b1

test:
  secret_key_base: 9ac65ad3a4c5eb6236e67e4f859ac983d6886989701efe10880160be89fa304e37da20d4ddc0418f9be527d62e0d124001a30e4d212b40ac7e8500ce755a7304

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= File.read(File.expand_path("~/.reportbooru/secret_key_base")) %>
